app:
  debug: true

grpcapi:
  target: "localhost:8082"
  dialtimeout: 10 # Seconds
  attempts: 6

tgbot:
  debug: false
  paginationstep: 5

kafka:
  # capacity: 512
  topic: "omp-tgbot-commands"
  # groupId: "logistic-package-api"
  brokers:
    # - "kafka:9092"
    - "localhost:9094"