app:
  debug: true

grpcapi:
  target: "localhost:8082"
  dialtimeout: 10 # Seconds
  attempts: 6

tgbot:
  debug: false
  paginationstep: 5

kafka:
  # capacity: 512
  # groupId: "logistic-package-api"
  attempts: 5
  tgCommandTopic: "omp-tgbot-commands"
  cacheEventTopic: "omp-tgbot-cache-events"
  brokers:
    # - "kafka:9092"
    - "localhost:9094"

redis:
  host: localhost
  port: 6379
  password: 
  DB: 0